---
version: "3"

# NOTE:
# - you cannot use network_mode=host (to optimize out network overhead) because hadoop does not work without DNS.

services:
  # hdfs / remote fs
  hdfs:
    image: gchq/hdfs:3.3
    command: namenode
    container_name: hdfs-namenode
    ports:
      - 9871:9870
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    volumes:
      - ./hdfs:/etc/hadoop/conf:ro
      - /var/log/hadoop
      - /data1
      - /data2

  hdfs-datanode:
    depends_on:
      - hdfs
    image: gchq/hdfs:3.3
    command: datanode
    container_name: hdfs-datanode
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    volumes:
      - ./hdfs:/etc/hadoop/conf:ro
      - /var/log/hadoop
      - /data1
      - /data2

  # foundation db / catalog
  fdb:
    image: foundationdb/foundationdb:7.1.24
    environment:
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR_PORT: 4550
      FDB_PORT: 4550
    container_name: fdb-0

  # byconity:
  tso:
    image: byconity/byconity:0.1.0-GA
    environment:
      PATH: /usr/sbin:/usr/bin:/sbin:/bin:/opt/byconity/bin
    command: bash -c "fdbcli -C /config/fdb.cluster --exec \"configure new single ssd\"; tso-server --config-file /config/tso.yml"
    depends_on:
      - fdb
      - hdfs
    volumes:
      - ./simple/:/config/:ro
    container_name: tso-0

  server:
    image: byconity/byconity:0.1.0-GA
    environment:
      PATH: /usr/sbin:/usr/bin:/sbin:/bin:/opt/byconity/bin
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 tso-0:18845 && clickhouse-server --config-file /config/server.yml"
    depends_on:
      - tso
      - hdfs
    ports:
      - "9000:52145"
      - "8124:21557"
    container_name: server-0
    volumes:
      - ./simple/:/config/:ro

  worker-write:
    image: byconity/byconity:0.1.0-GA
    environment:
      PATH: /usr/sbin:/usr/bin:/sbin:/bin:/opt/byconity/bin
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server:21557 && clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: worker-write-0
    volumes:
      - ./simple/:/config/:ro

  worker-default:
    image: byconity/byconity:0.1.0-GA
    environment:
      PATH: /usr/sbin:/usr/bin:/sbin:/bin:/opt/byconity/bin
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server:21557 && clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: worker-default-0
    volumes:
      - ./simple/:/config/:ro

  daemon-manager:
    image: byconity/byconity:0.1.0-GA
    environment:
      PATH: /usr/sbin:/usr/bin:/sbin:/bin:/opt/byconity/bin
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server:21557 && daemon-manager --config-file ./config/daemon-manager.yml"
    depends_on:
      - server
    container_name: daemon-manager-0
    volumes:
      - ./simple/:/config/:ro
